# Generated by Django 4.0.3 on 2022-04-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='apellido',
            field=models.CharField(default='ingrese apellido', max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(default='ingrese nombre', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='relacion',
            field=models.CharField(default='ingrese parentesco', max_length=30, verbose_name='Parentesco'),
        ),
    ]
